{
 "title": "App | Game Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sep_count{type=\"user\"}"
    }
   ]
  },
  {
   "title": "PCs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sep_count{type=\"pc\"}"
    }
   ]
  },
  {
   "title": "MPs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sep_count{type=\"mp\"}"
    }
   ]
  },
  {
   "title": "Squads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sep_count{type=\"squad\"}"
    }
   ]
  },
  {
   "title": "Items",
   "type": "singlestat",
   "description": "sum(gear + weapon)",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sep_count{type=~\"gear|weapon\"})"
    }
   ]
  }
 ]
}