INSERT INTO weaponsMeta
(id, name, mastery, onehanded, ranged, rng, pas_use, pas_reload, moddable, caliber, rounds, burst_acc, size, dmg_base, dmg_sneaky, parry, arpen, defcan, rarity)
VALUES
(1, 'Revolver', NULL,  True,  True,    2, 4,    2, True, '22 LR',    1,    0, '1x2',  70, 0, 0, 0, 0, 5),
(2,  'Espadon', NULL, False, False, NULL, 8, NULL, True,    NULL, NULL, NULL, '3x4', 120, 0, 0, 5, 0, 3)
